name: A Slice of README
description: Personal Space
author: Boyang Niu
author_email: boyang.niu@gmail.com
category_dir: /
baseurl: 
url: http://boyangniu.me/
markdown: rdiscount
permalink: pretty
paginate: 3
category_title_prefix: "Tagged - "
category_meta_description_prefix: "Tagged - "
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
gems: ['jekyll-less', 'jekyll-sitemap']
highlighter: pygments
markdown: redcarpet